### ISSUE TITLE
Suggestion: Support Internationalized domain names (IDN)

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/module-phpbrowser#42]
Right now, this is not working:
```yaml
- REST:
    depends: PhpBrowser
    url: 'https://fööbär.localhost/'
```

If this gets changed, the note I just added in https://github.com/Codeception/module-phpbrowser/pull/41 needs to be deleted ;-)
